"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RoyaltyAutoClaimProxy__factory = exports.MockToken__factory = exports.royaltyAutoClaimSol = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.royaltyAutoClaimSol = require("./RoyaltyAutoClaim.sol");
var MockToken__factory_1 = require("./MockToken__factory");
Object.defineProperty(exports, "MockToken__factory", { enumerable: true, get: function () { return MockToken__factory_1.MockToken__factory; } });
var RoyaltyAutoClaimProxy__factory_1 = require("./RoyaltyAutoClaimProxy__factory");
Object.defineProperty(exports, "RoyaltyAutoClaimProxy__factory", { enumerable: true, get: function () { return RoyaltyAutoClaimProxy__factory_1.RoyaltyAutoClaimProxy__factory; } });
