/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as royaltyAutoClaimSol from "./RoyaltyAutoClaim.sol";
export { RoyaltyAutoClaimProxy__factory } from "./RoyaltyAutoClaimProxy__factory";
