/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRegistrationVerifier } from "./IRegistrationVerifier";
export type { RegistrationVerifier } from "./RegistrationVerifier";
