"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MockToken__factory = exports.RoyaltyAutoClaim__factory = exports.IRoyaltyAutoClaim__factory = exports.RoyaltyAutoClaimProxy__factory = exports.factories = void 0;
exports.factories = require("./factories");
var RoyaltyAutoClaimProxy__factory_1 = require("./factories/RoyaltyAutoClaimProxy__factory");
Object.defineProperty(exports, "RoyaltyAutoClaimProxy__factory", { enumerable: true, get: function () { return RoyaltyAutoClaimProxy__factory_1.RoyaltyAutoClaimProxy__factory; } });
var IRoyaltyAutoClaim__factory_1 = require("./factories/RoyaltyAutoClaim.sol/IRoyaltyAutoClaim__factory");
Object.defineProperty(exports, "IRoyaltyAutoClaim__factory", { enumerable: true, get: function () { return IRoyaltyAutoClaim__factory_1.IRoyaltyAutoClaim__factory; } });
var RoyaltyAutoClaim__factory_1 = require("./factories/RoyaltyAutoClaim.sol/RoyaltyAutoClaim__factory");
Object.defineProperty(exports, "RoyaltyAutoClaim__factory", { enumerable: true, get: function () { return RoyaltyAutoClaim__factory_1.RoyaltyAutoClaim__factory; } });
var MockToken__factory_1 = require("./factories/MockToken__factory");
Object.defineProperty(exports, "MockToken__factory", { enumerable: true, get: function () { return MockToken__factory_1.MockToken__factory; } });
